### ISSUE TITLE
Cleanup zip file

### ISSUE THREAD

**Issue by baado** [DeNADev/capistrano-net_storage#9]
Thank you for your nice gem :)
But, one problem happened.
If for some reason an error occurred during deployment, the zip file remained in the `releases` directory.
If the zip file remained in the `releases` directory, the capistrano cleanup task does not work properly, so the `releases` directory continues to increase, because the zip file name does not match `/^\d{14}$/`.
https://github.com/capistrano/capistrano/blob/92bfd1156820636921800534e70d633d16ddbe37/lib/capistrano/tasks/deploy.rake#L148-L178

We deal with this by defining a small capistrano task like above.

```rb
namespace :deploy do
  desc "Clean up releases directory"
  task :cleanup_releases_directory do
    on roles(:app) do
      releases = capture(:ls, releases_path, "-1")
      releases.lines do |release|
        unless release.match(/\d{14}$/)
          execute :rm, "-rf", File.join(releases_path, release)
        end
      end
    end
  end
end

before 'deploy:cleanup', 'deploy:cleanup_releases_directory'
```

I am glad if gem is corresponded to this!

**Comment by aeroastro** [comment]
@baado 
Sorry for the late reply.
This issue has been fixed by #12.

Now the zip file will be saved in `#{deploy_to}/net_storage_archives` as documented in CHANGELOG.md
https://github.com/DeNADev/capistrano-net_storage/blob/ef70642919cf188b71b1335be286771dab84b0da/CHANGELOG.md#040-20220517

Capistrano::NetStorage will handle its generating files from now on.
Regarding the current zip file under `#{deploy_to}/releases`, if any, could you remove that manually?

The file deleting functionality for previous versions (< 0.4.0) has not been implemented in order to avoid false positives.

**Comment by aeroastro** [comment]
And, unfortunately, we found some issues regarding #12.
Now we are investigating the details, and we would like you to suspend updating Capistrano::NetStorage

**Comment by baado** [comment]
Thank you for your correspondence!
I also understand that there was some issues.
On the other hand, I am sorry to say that I am already not where this gem is needed, so there is no hurry to respond
Thank you! :)

**Comment by aeroastro** [comment]
Sorry for the late response.
We have found out that #12 is O.K. to solve this issue.

**Comment by baado** [comment]
Thanks for addressing this issue!
And thank you for the mention!
